// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OnlineMeeting/internal/meeting/dao/internal"
	"OnlineMeeting/internal/meeting/model/entity"
	"context"
	"fmt"

	"github.com/gogf/gf/v2/errors/gerror"
)

// tMeetingParticipantDao is the data access object for the table t_meeting_participant.
// You can define custom methods on it to extend its functionality as needed.
type tMeetingParticipantDao struct {
	*internal.TMeetingParticipantDao
}

var (
	// TMeetingParticipant is a globally accessible object for table t_meeting_participant operations.
	TMeetingParticipant = tMeetingParticipantDao{internal.NewTMeetingParticipantDao()}
)

// Add your custom methods and functionality below.
func (t *tMeetingParticipantDao) GetByRoomNumber(ctx context.Context, roomNumber string) (res []*entity.MeetingParticipantDB, err error) {
	m := t.Ctx(ctx).Where(TMeetingParticipant.Columns().MRoomNumber, roomNumber)
	res = make([]*entity.MeetingParticipantDB, 0)
	if err = m.Scan(&res); err != nil {
		return nil, gerror.New(fmt.Sprintf("tMeetingParticipantDao.GetByRoomNumber: %v", err.Error()))
	}
	return
}

func (t *tMeetingParticipantDao) GetByUserID(ctx context.Context, userID string) (res []*entity.MeetingParticipantDB, err error) {
	m := t.Ctx(ctx).Where(TMeetingParticipant.Columns().UserId, userID)
	res = make([]*entity.MeetingParticipantDB, 0)
	if err = m.FieldsEx(TMeetingParticipant.Columns().Id).Scan(&res); err != nil {
		return nil, gerror.New(fmt.Sprintf("tMeetingParticipantDao.GetByUserID: %v", err.Error()))
	}
	return
}
