// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OnlineMeeting/internal/meeting/dao/internal"
)

// tMeetingDao is the data access object for the table t_meeting.
// You can define custom methods on it to extend its functionality as needed.
type tMeetingDao struct {
	*internal.TMeetingDao
}

var (
	// TMeeting is a globally accessible object for table t_meeting operations.
	TMeeting = tMeetingDao{internal.NewTMeetingDao()}
)

// Add your custom methods and functionality below.
