// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OnlineMeeting/internal/meeting/dao/internal"
)

// tMeetingParticipantDao is the data access object for the table t_meeting_participant.
// You can define custom methods on it to extend its functionality as needed.
type tMeetingParticipantDao struct {
	*internal.TMeetingParticipantDao
}

var (
	// TMeetingParticipant is a globally accessible object for table t_meeting_participant operations.
	TMeetingParticipant = tMeetingParticipantDao{internal.NewTMeetingParticipantDao()}
)

// Add your custom methods and functionality below.
